# Generated by Django 4.2.7 on 2023-12-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('TEACHER', 'Учитель'), ('STUDENT', 'Ученик')], default=None, max_length=255),
        ),
    ]
