# Generated by Django 4.2.7 on 2023-12-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_role_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to='user.customuser')),
                ('bio', models.DateField(blank=True, null=True)),
                ('pob', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('ml', 'male'), ('fm', 'female')], default='ml', max_length=2)),
                ('nation', models.CharField(choices=[('kazakh', 'Казах/Казашка'), ('russian', 'Русский/Русская')], default='kazakh', max_length=100, verbose_name='Национальность')),
                ('citizenship', models.CharField(max_length=100)),
                ('iin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Профиль учителя',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
