# Generated by Django 4.2.7 on 2023-12-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_teacherprofile_customuser_surname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='EmployeeProfile',
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': 'Профиль сотрудника'},
        ),
    ]
